// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onxqwogsndvndfttlqhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ueHF3b2dzbmR2bmRmdHRscWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjUyNDksImV4cCI6MjA2NTMwMTI0OX0.CjBJMdAc2LoidgLd3Trc_ZKEZ7NrU5o8jvJp6u7kHkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);